name: tondo
description: Plateforme artisans Burkina Faso
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  firebase_messaging: ^14.7.0

  # Ã‰tat
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Navigation
  go_router: ^12.1.0

  # UI
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0

  # Utilitaires
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true